# Site Settings
title: "Westhouse"
title_separator: "|"
name: "Westhouse"
description:
url: https://www.westhousehotelnewyork.com
repository: "TravelTripperWeb-Sites/westhouse2"
reztripUrl: "https://westhousehotelnewyork.reztrip.com/"

# Language Settings
default_lang: 'en'
languages: ['en']

# Reading Files
include:
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - Makefile
  - media.json
  - models.json
  - node_modules
  - old_media.json
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - sitemap.json
  - tmp
  - vendor
keep_files:
  - .git
  - assets
rsync_copy:
- _assets
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  load_paths:
    - _sass
  style: compressed

# Outputting
permalink: pretty
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

data_paginate:
  per_page: 20
  data: 'blog'
  path: 'blog/page:num'
  pagination_template: 'blog/index.html'
  sort_field: 'datemeta'
  sort_reverse: true

page_gen:
  - data: 'gallery-category'
    template: 'gallery-single'
    dir: '/gallery'
  - data: 'amenities'
    template: 'amenities-single'
    dir: '/amenities'
  - data: 'dining'
    template: 'dining-single'
    dir: '/dining'
  - data: 'area'
    template: 'area-single'
    dir: '/things-to-do-in-nyc'
  - data: 'blog'
    template: 'blog-single'
    dir: '/blog'
  - data: 'partners'
    template: 'partner-single'
    dir: '/partners'
  - data: 'events'
    template: 'event-single'
    dir: '/events-in-nyc'
  - data: 'neighborhood-locations'
    template: 'neighborhood-single'
    dir: '/attractions'
  - data: 'culinary-guide'
    template: 'culinary-single'
    dir: '/things-to-do-in-nyc/culinary-guide'
port: 4040